# Generated by Django 4.2.5 on 2023-11-14 01:21

from django.db import migrations, models
import main.services.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_user_avatar_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="main.tag"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=main.services.storage_backends.public_storage,
                upload_to="",
            ),
        ),
    ]
