# Generated by Django 4.2.3 on 2023-08-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_user_date_of_birth_user_phone_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(to="main.tag"),
        ),
    ]
