# Generated by Django 4.2.3 on 2023-08-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_user_date_of_birth_user_phone_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
